print("hello world")
print("shyam")
print("silver oak university")
print("wellcome to programming")
print(1)
print(2)
print(3)
print(4)
print(5)
print("i love paython")
print("thusday")
print("data analaysis")
print("thusdayLearning Python is easy")
print("ahmedabad")
